import { WORDS } from './words.js?v=20260920-2';
const $=s=>document.querySelector(s); const LS=localStorage;
let authMode='login', currentUser=null, queue=[], current=null, quizAnswered=false, streak=0;
const svgFor=(w)=>`<svg viewBox="0 0 600 360" role="img" aria-label="${w.word}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${w.colors[0]}"/><stop offset="1" stop-color="${w.colors[1]}"/></linearGradient></defs><rect width="600" height="360" fill="url(#g)"/><circle cx="510" cy="75" r="38" fill="#fff8"/><text x="300" y="185" text-anchor="middle" font-size="98">${w.emoji}</text><text x="300" y="285" text-anchor="middle" font-size="28" font-weight="700" fill="#193127">${w.hint}</text></svg>`;
const users=()=>JSON.parse(LS.getItem('wg_users')||'{}'); const saveUsers=u=>LS.setItem('wg_users',JSON.stringify(u));
const key=()=>`wg_progress_${currentUser}`; const progress=()=>JSON.parse(LS.getItem(key())||'{}'); const saveProgress=p=>LS.setItem(key(),JSON.stringify(p));
function setAuth(mode){authMode=mode;$('#loginTab').classList.toggle('active',mode==='login');$('#registerTab').classList.toggle('active',mode==='register');$('#authSubmit').textContent=mode==='login'?'登录并开始':'注册并开始';$('#authMsg').textContent=''}
$('#loginTab').onclick=()=>setAuth('login'); $('#registerTab').onclick=()=>setAuth('register');
$('#authForm').onsubmit=e=>{e.preventDefault();const name=$('#username').value.trim(),pass=$('#password').value;const u=users();if(authMode==='register'){if(u[name])return $('#authMsg').textContent='用户名已存在';u[name]=btoa(unescape(encodeURIComponent(pass)));saveUsers(u)}else if(!u[name]||u[name]!==btoa(unescape(encodeURIComponent(pass))))return $('#authMsg').textContent='用户名或密码不正确';currentUser=name;LS.setItem('wg_current',name);showGame()};
function showGame(){ $('#authView').classList.add('hidden');$('#gameView').classList.remove('hidden');$('#welcome').textContent=`你好，${currentUser}`;buildQueue();renderStats()}
function buildQueue(){const level=$('#levelSelect').value,p=progress(),now=Date.now();let list=WORDS.filter(w=>level==='all'||w.level===level);if(level==='review')list=WORDS.filter(w=>{const x=p[w.word];return x&&(x.strength<3||x.due<=now)});queue=list.sort((a,b)=>{const A=p[a.word]||{due:0,strength:0},B=p[b.word]||{due:0,strength:0};return A.due-B.due||A.strength-B.strength||Math.random()-.5});if(!queue.length) queue=WORDS.filter(w=>level==='all'||w.level===level);nextCard()}
function nextCard(){current=queue.shift()||WORDS[Math.floor(Math.random()*WORDS.length)];queue.push(current);quizAnswered=false;renderCard()}
function renderCard(){const p=progress()[current.word]||{};$('#imageBox').innerHTML=svgFor(current);$('#wordText').textContent=current.word;$('#phonetic').textContent=current.phonetic;$('#meaning').textContent=current.meaning;$('#example').textContent=current.example;$('#levelBadge').textContent={easy:'简单',medium:'中等',hard:'困难'}[current.level];const done=Object.keys(progress()).length;$('#progressText').textContent=`已接触 ${done} / ${WORDS.length} 个单词`;$('#progressBar').style.width=`${Math.min(100,done/WORDS.length*100)}%`;const quiz=$('#modeSelect').value==='quiz';$('#learnActions').classList.toggle('hidden',quiz);$('#quizActions').classList.toggle('hidden',!quiz);$('#meaning').classList.toggle('hidden',quiz);$('#example').classList.toggle('hidden',quiz);$('#quizOptions').classList.toggle('hidden',!quiz);$('#feedback').textContent='';if(quiz)makeQuiz()}
function makeQuiz(){const opts=[current,...WORDS.filter(w=>w.word!==current.word).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);$('#quizOptions').innerHTML=opts.map(w=>`<button data-word="${w.word}">${w.meaning}</button>`).join('');$('#quizOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>answerQuiz(b))}
function answerQuiz(btn){if(quizAnswered)return;quizAnswered=true;const ok=btn.dataset.word===current.word;btn.classList.add(ok?'correct':'wrong');$('#quizOptions').querySelectorAll('button').forEach(b=>{if(b.dataset.word===current.word)b.classList.add('correct')});$('#meaning').classList.remove('hidden');$('#example').classList.remove('hidden');rate(ok?'good':'again');$('#feedback').textContent=ok?'回答正确！':'这次没答对，系统会更快安排它再次出现。'}
function rate(type){const p=progress(),x=p[current.word]||{seen:0,strength:0,wrong:0,due:0};x.seen++;let hours=0;if(type==='again'){x.strength=Math.max(0,x.strength-1);x.wrong++;hours=.1;streak=0}else if(type==='hard'){x.strength=Math.max(1,x.strength);hours=6;streak=0}else{x.strength=Math.min(5,x.strength+1);hours=[0,8,24,72,168,336][x.strength]||336;streak++}x.due=Date.now()+hours*3600000;p[current.word]=x;saveProgress(p);renderStats();if($('#modeSelect').value==='learn')nextCard()}
function renderStats(){const vals=Object.values(progress());$('#learnedCount').textContent=vals.length;$('#masteredCount').textContent=vals.filter(x=>x.strength>=3).length;$('#reviewCount').textContent=vals.filter(x=>x.strength<3||x.due<=Date.now()).length;$('#streakCount').textContent=streak}
document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rate(b.dataset.rate));$('#nextQuiz').onclick=()=>nextCard();$('#levelSelect').onchange=buildQueue;$('#modeSelect').onchange=renderCard;$('#logoutBtn').onclick=()=>{LS.removeItem('wg_current');location.reload()};$('#resetBtn').onclick=()=>{if(confirm('确定重置当前用户的学习记录吗？')){LS.removeItem(key());streak=0;buildQueue();renderStats()}};
currentUser=LS.getItem('wg_current');if(currentUser&&users()[currentUser])showGame();