import { WORDS } from './words.js?v=20260920-2';
const $=s=>document.querySelector(s); const LS=localStorage;
let authMode='login', currentUser=null, queue=[], current=null, quizAnswered=false, streak=0, activeWords=[];
const svgFor=(w)=>`<svg viewBox="0 0 600 360" role="img" aria-label="${w.word}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${w.colors[0]}"/><stop offset="1" stop-color="${w.colors[1]}"/></linearGradient></defs><rect width="600" height="360" fill="url(#g)"/><circle cx="510" cy="75" r="38" fill="#fff8"/><text x="300" y="185" text-anchor="middle" font-size="98">${w.emoji}</text><text x="300" y="285" text-anchor="middle" font-size="28" font-weight="700" fill="#193127">${w.meaning}</text></svg>`;
const customKey=()=>`wg_custom_words_${currentUser}`;function getWords(){const saved=currentUser?JSON.parse(LS.getItem(customKey())||'null'):null;return saved&&saved.length?saved:WORDS}function hydrateWords(){activeWords=getWords()}
const users=()=>JSON.parse(LS.getItem('wg_users')||'{}'); const saveUsers=u=>LS.setItem('wg_users',JSON.stringify(u));
const key=()=>`wg_progress_${currentUser}`; const progress=()=>JSON.parse(LS.getItem(key())||'{}'); const saveProgress=p=>LS.setItem(key(),JSON.stringify(p));
function setAuth(mode){authMode=mode;$('#loginTab').classList.toggle('active',mode==='login');$('#registerTab').classList.toggle('active',mode==='register');$('#authSubmit').textContent=mode==='login'?'登录并开始':'注册并开始';$('#authMsg').textContent=''}
$('#loginTab').onclick=()=>setAuth('login'); $('#registerTab').onclick=()=>setAuth('register');
$('#authForm').onsubmit=e=>{e.preventDefault();const name=$('#username').value.trim(),pass=$('#password').value;const u=users();if(authMode==='register'){if(u[name])return $('#authMsg').textContent='用户名已存在';u[name]=btoa(unescape(encodeURIComponent(pass)));saveUsers(u)}else if(!u[name]||u[name]!==btoa(unescape(encodeURIComponent(pass))))return $('#authMsg').textContent='用户名或密码不正确';currentUser=name;LS.setItem('wg_current',name);showGame()};
function showGame(){hydrateWords(); $('#authView').classList.add('hidden');$('#gameView').classList.remove('hidden');$('#welcome').textContent=`你好，${currentUser}`;buildQueue();renderStats()}
function buildQueue(){const p=progress();const unique=[...new Map(activeWords.map(w=>[w.word,w])).values()];queue=unique.sort((a,b)=>{const A=p[a.word]||{due:0,strength:0},B=p[b.word]||{due:0,strength:0};return A.due-B.due||A.strength-B.strength||Math.random()-.5});nextCard()}
function nextCard(){const previous=current?.id||current?.word;let candidate=queue.shift()||activeWords[Math.floor(Math.random()*activeWords.length)];let guard=0;while(previous&&(candidate.id||candidate.word)===previous&&queue.length&&guard++<queue.length){queue.push(candidate);candidate=queue.shift()}current=candidate;queue.push(current);quizAnswered=false;renderCard()}
function renderCard(){const p=progress()[current.word]||{};$('#imageBox').innerHTML=svgFor(current);$('#wordText').textContent=current.word;$('#phonetic').textContent=current.phonetic;$('#meaning').textContent=current.meaning;$('#example').textContent=current.example;$('#levelBadge').textContent={easy:'简单',medium:'中等',hard:'困难'}[current.level];const total=new Set(activeWords.map(w=>w.word)).size,done=Object.keys(progress()).filter(k=>activeWords.some(w=>w.word===k)).length;$('#progressText').textContent=`已接触 ${Math.min(done,total)} / ${total} 个单词`;$('#progressBar').style.width=`${Math.min(100,Math.min(done,total)/total*100)}%`;const mode=$('#modeSelect').value,quiz=mode==='quiz',typing=mode==='type';$('#learnActions').classList.toggle('hidden',quiz||typing);$('#quizActions').classList.toggle('hidden',!quiz);$('#quizOptions').classList.toggle('hidden',!quiz);$('#typeAnswer').classList.toggle('hidden',!typing);$('#answerDetails').classList.toggle('hidden',typing||quiz);$('#feedback').textContent='';if(typing){$('#spellingInput').value='';setTimeout(()=>$('#spellingInput').focus(),0)}if(quiz)makeQuiz()}
function makeQuiz(){const opts=[current,...activeWords.filter(w=>w.word!==current.word).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);$('#quizOptions').innerHTML=opts.map(w=>`<button data-word="${w.word}">${w.meaning}</button>`).join('');$('#quizOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>answerQuiz(b))}
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;
function speakCorrect(){if(!('speechSynthesis'in window)){$('#voiceStatus').textContent='当前浏览器不支持语音播放';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.word);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
function celebrate(){const el=$('#celebration');el.classList.remove('hidden');el.classList.remove('play');void el.offsetWidth;el.classList.add('play');try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){const ctx=new AC(),now=ctx.currentTime;[[523.25,0],[659.25,.11],[783.99,.22]].forEach(([freq,delay])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,now+delay);g.gain.exponentialRampToValueAtTime(.16,now+delay+.015);g.gain.exponentialRampToValueAtTime(.0001,now+delay+.18);o.connect(g);g.connect(ctx.destination);o.start(now+delay);o.stop(now+delay+.2)});setTimeout(()=>ctx.close(),700)}}catch{}setTimeout(()=>{el.classList.add('hidden');el.classList.remove('play')},1600)}
function finishAnswer(ok,heard=''){const answered=current;$('#answerDetails').classList.remove('hidden');$('#playPronunciation').classList.toggle('hidden',ok);$('#feedback').textContent=ok?'回答正确！':heard?`识别为“${heard}”，正确答案：${answered.word}`:'正确答案：'+answered.word;rate(ok?'good':'again');$('#spellingInput').disabled=true;$('#checkSpelling').textContent='下一题';$('#checkSpelling').onclick=advanceAfterAnswer;if(ok){celebrate();setTimeout(()=>{if(current===answered)advanceAfterAnswer()},2000)}}
function advanceAfterAnswer(){resetTypeControls();nextCard()}
function startVoice(){if(!SpeechRecognition){$('#voiceStatus').textContent='当前浏览器暂不支持语音识别，请使用文字输入。';return}if(recognition){try{recognition.stop()}catch{}return}recognition=new SpeechRecognition();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=3;$('#voiceInput').classList.add('listening');$('#voiceLabel').textContent='正在听…';$('#voiceStatus').textContent='请清晰读出这个英文单词';recognition.onresult=e=>{const heard=Array.from(e.results[0]).map(x=>x.transcript.trim().toLowerCase().replace(/[^a-z'-]/g,'')).filter(Boolean);const target=current.word.toLowerCase();const ok=heard.includes(target);$('#voiceStatus').textContent=ok?`✓ 识别正确：${target}`:`识别结果：${heard[0]||'未识别'}`;finishAnswer(ok,heard[0]||'')};recognition.onerror=e=>{$('#voiceStatus').textContent=e.error==='not-allowed'?'需要允许浏览器使用麦克风':'没有听清，请再试一次'};recognition.onend=()=>{recognition=null;$('#voiceInput').classList.remove('listening');$('#voiceLabel').textContent='语音读单词'};try{recognition.start()}catch{recognition=null}}
function checkSpelling(){const input=$('#spellingInput').value.trim().toLowerCase();if(!input)return;const ok=input===current.word.toLowerCase();finishAnswer(ok,input)}
function resetTypeControls(){$('#spellingInput').disabled=false;$('#spellingInput').value='';$('#checkSpelling').textContent='提交';$('#checkSpelling').onclick=checkSpelling;$('#voiceStatus').textContent='';$('#feedback').textContent='';$('#playPronunciation').classList.add('hidden');if(recognition){try{recognition.abort()}catch{}recognition=null}$('#voiceInput').classList.remove('listening');$('#voiceLabel').textContent='语音读单词'}
function answerQuiz(btn){if(quizAnswered)return;quizAnswered=true;const ok=btn.dataset.word===current.word;btn.classList.add(ok?'correct':'wrong');$('#quizOptions').querySelectorAll('button').forEach(b=>{if(b.dataset.word===current.word)b.classList.add('correct')});$('#meaning').classList.remove('hidden');$('#example').classList.remove('hidden');rate(ok?'good':'again');$('#feedback').textContent=ok?'回答正确！':'这次没答对，系统会更快安排它再次出现。'}
function rate(type){const p=progress(),x=p[current.word]||{seen:0,strength:0,wrong:0,due:0};x.seen++;let hours=0;if(type==='again'){x.strength=Math.max(0,x.strength-1);x.wrong++;hours=.1;streak=0}else if(type==='hard'){x.strength=Math.max(1,x.strength);hours=6;streak=0}else{x.strength=Math.min(5,x.strength+1);hours=[0,8,24,72,168,336][x.strength]||336;streak++}x.due=Date.now()+hours*3600000;p[current.word]=x;saveProgress(p);renderStats();if($('#modeSelect').value==='learn')nextCard()}
function renderStats(){const vals=Object.values(progress());$('#learnedCount').textContent=vals.length;$('#masteredCount').textContent=vals.filter(x=>x.strength>=3).length;$('#reviewCount').textContent=vals.filter(x=>x.strength<3||x.due<=Date.now()).length;$('#streakCount').textContent=streak}
function parseCustomWords(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).map((line,n)=>{const parts=line.split(/[,，\t|]/).map(x=>x.trim());const word=(parts[0]||'').toLowerCase();const meaning=parts[1]||word;if(!/^[a-z][a-z'-]*$/.test(word))return null;return{id:'custom-'+word,word,meaning,phonetic:'',emoji:'📝',example:`Practice the word ${word}.`,colors:[['#dcefdc','#f8f1cc'],['#dce9f5','#eef4ff'],['#f7ddda','#f8efdc']][n%3]}}).filter(Boolean)}
function saveCustom(){const list=parseCustomWords($('#customWordsInput').value);if(!list.length){$('#customWordsMsg').textContent='请至少输入一个有效英文单词';return}const unique=[...new Map(list.map(w=>[w.word,w])).values()];LS.setItem(customKey(),JSON.stringify(unique));hydrateWords();$('#customWordsMsg').textContent=`已保存 ${unique.length} 个单词`;buildQueue();renderStats()}
function clearCustom(){LS.removeItem(customKey());$('#customWordsInput').value='';hydrateWords();$('#customWordsMsg').textContent='已恢复5个测试单词';buildQueue();renderStats()}
function loadCustomEditor(){const saved=JSON.parse(LS.getItem(customKey())||'null');$('#customWordsInput').value=saved?saved.map(w=>`${w.word},${w.meaning}`).join('\n'):''}
function setSettings(open){if(open)loadCustomEditor();$('#settingsPanel').classList.toggle('open',open);$('#settingsBackdrop').classList.toggle('open',open)}$('#settingsBtn').onclick=()=>setSettings(true);$('#saveCustomWords').onclick=saveCustom;$('#clearCustomWords').onclick=clearCustom;$('#closeSettings').onclick=()=>setSettings(false);$('#settingsBackdrop').onclick=()=>setSettings(false);
document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rate(b.dataset.rate));$('#nextQuiz').onclick=()=>nextCard();$('#checkSpelling').onclick=checkSpelling;$('#voiceInput').onclick=startVoice;$('#playPronunciation').onclick=speakCorrect;$('#spellingInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if($('#spellingInput').disabled)advanceAfterAnswer();else checkSpelling()}});$('#modeSelect').onchange=()=>{resetTypeControls();renderCard();setSettings(false)};$('#logoutBtn').onclick=()=>{LS.removeItem('wg_current');location.reload()};$('#resetBtn').onclick=()=>{if(confirm('确定重置当前用户的学习记录吗？')){LS.removeItem(key());streak=0;buildQueue();renderStats()}};
currentUser=LS.getItem('wg_current');if(currentUser&&users()[currentUser])showGame();